// Validation primitives used by route validators

export type ValidationCode =
  | "INVALID_JSON_BODY"
  | "NAME_REQUIRED"
  | "NAME_TOO_LONG"
  | "SUBJECT_INVALID"
  | "SUBJECT_TOO_LONG"
  | "DESCRIPTION_INVALID"
  | "DESCRIPTION_TOO_LONG"
  | "DEFAULT_FEE_INVALID"
  | "IS_ACTIVE_INVALID"
  | "SORT_INVALID"
  | "EMAIL_REQUIRED"
  | "EMAIL_INVALID"
  | "PASSWORD_REQUIRED"
  | "PASSWORD_TOO_SHORT"
  | "NAME_INVALID"
  | "NAME_TOO_LONG"
  // Student-specific
  | "PHONE_INVALID"
  | "NOTE_TOO_LONG"
  | "RELATIONSHIP_INVALID"
  | "PARENT_NAME_INVALID"
  | "PARENT_EMAIL_INVALID"
  | "PARENT_PHONE_INVALID"
  | "PARENT_NOTE_TOO_LONG"
  // ClassStudent-specific
  | "STUDENT_ID_REQUIRED"
  | "UNIT_PRICE_INVALID"
  // Session-specific
  | "START_TIME_REQUIRED"
  | "DURATION_INVALID"
  | "DURATION_TOO_SHORT"
  | "FEE_INVALID"
  | "FEE_NEGATIVE"
  | "NOTES_INVALID"
  | "NOTES_TOO_LONG"
  | "STATUS_INVALID"
  | "TYPE_INVALID"
  | "DAYS_OF_WEEK_INVALID"
  | "DAYS_OF_WEEK_REQUIRED"
  | "TIME_REQUIRED"
  | "TIME_FORMAT_INVALID"
  | "START_DATE_REQUIRED"
  | "END_DATE_INVALID"
  | "DATE_FORMAT_INVALID"
  | "MAX_OCCURRENCES_INVALID"
  | "MAX_OCCURRENCES_TOO_SMALL"
  | "TIMEZONE_INVALID"
  | "EXCLUSION_DATE_INVALID";

export type ValidationField =
  | "body"
  | "query"
  | "name"
  | "subject"
  | "description"
  | "defaultFeePerSession"
  | "isActive"
  | "sort"
  | "email"
  | "password"
  | "oldPassword"
  | "newPassword"
  // Student-specific
  | "phone"
  | "note"
  | "parentInline.relationship"
  | "parentInline.name"
  | "parentInline.email"
  | "parentInline.phone"
  | "parentInline.note"
  // ClassStudent-specific
  | "studentId"
  | "unitPriceOverride"
  // Session-specific
  | "startTime"
  | "durationMin"
  | "feePerSession"
  | "notes"
  | "status"
  | "type"
  | "recurrence.daysOfWeek"
  | "recurrence.time"
  | "recurrence.startDate"
  | "recurrence.endDate"
  | "recurrence.maxOccurrences"
  | "recurrence.timezone"
  | "recurrence.exclusionDates";

export type ValidationErrorDetail = {
  field: ValidationField;
  code: ValidationCode;
  message: string;
};
