export const CLASS_REMARK_TEMPLATE_MATRIX: (string | number)[][] = [
  // Row 1 (headers)
  [
    "",
    "Câu khen",
    "",
    "Câu BTVN",
    "",
    "Câu dạng bài làm tốt",
    "",
    "",
    "Câu dạng bài chưa làm tốt",
    "Câu kết",
    "",
    "Nhận xét",
  ],
  // Row 2 (templates)
  [
    "Tên bài thi: bài thi giữa học kỳ 1",
    "Con {Tên học sinh} hăng hái phát biểu và tham gia tích cực các hoạt động học tập trên lớp",
    "Con {Tên học sinh} trả lời tốt các câu hỏi của cô trong giờ học, con hãy hăng hái phát biểu hơn nữa nhé.",
    "Con có ý thức học tốt và hoàn thành đầy đủ BTVN cô giao",
    "Con cần chăm chỉ hơn trong việc hoàn thành BTVN để củng cố kiến thức nhé",
    "Trong {Tên bài thi}, con làm tốt các dạng bài: {Các dạng bài làm tốt}",
    "",
    "",
    "Con cần ôn tập và rèn luyện thêm về: {Các dạng bài làm chưa tốt}",
    "Cô tin rằng con sẽ phát huy điểm mạnh của mình, cẩn thận hơn khi làm bài và chinh phục được thật nhiều điểm tốt con nhé.",
    "Cô tin rằng con sẽ cẩn thận hơn khi làm bài và có bứt phá trong thời gian tới nhé.",
    "",
  ],
  // Row 2b (optional templates v2 for testing variety)
  [
    "Tên bài thi: bài kiểm tra giữa kỳ",
    "{Tên học sinh} có tinh thần học tập nghiêm túc và chủ động trong các hoạt động trên lớp",
    "{Tên học sinh} tương tác tích cực trong giờ học, hãy tiếp tục phát huy sự tự tin khi phát biểu nhé.",
    "{Tên học sinh} hoàn thành đầy đủ và đúng hạn các bài tập về nhà",
    "Cần nỗ lực thêm để hoàn thành tốt hơn các bài tập về nhà nhằm củng cố kiến thức",
    "Trong {Tên bài thi}, con thể hiện tốt ở các dạng bài: {Các dạng bài làm tốt}",
    "",
    "",
    "Con nên tập trung rèn luyện thêm ở các dạng bài: {Các dạng bài làm chưa tốt}",
    "Cô ghi nhận sự cố gắng của con, hãy tiếp tục duy trì phong độ và sự cẩn thận khi làm bài nhé.",
    "Cô tin rằng với sự tập trung hơn, con sẽ có bước tiến rõ rệt trong thời gian tới.",
    "",
  ],
  // Row 3 (meta row: labels and problem types)
  [
    "Tên học sinh",
    "Tốt",
    "Chưa tốt",
    "Tốt",
    "Chưa tốt",
    "Điền đáp án",
    "Bài toán có lời văn",
    "Hình học phẳng",
    "",
    "Tốt",
    "Chưa tốt",
    "",
  ],
  // Row 4 (example student rows)
  [
    "Đức Trí",
    "x",
    "",
    "",
    "x",
    "x",
    "",
    "x",
    "",
    "",
    "x",
    "",
  ],
  [
    "Văn Toàn",
    "x",
    "",
    "x",
    "",
    "x",
    "x",
    "",
    "",
    "x",
    "",
    "",
  ],
];
